exams/urls.py
from django.conf.urls import url

from exams.views import ExamsList, ExamDetail

urlpatterns = [
    url(r'^$',
        ExamsList.as_view(),
        name='exams_list'),
    url(r'^(?P<pk>\d+)/?$',
        ExamDetail.as_view(),
        name='exam_detail'),
    ]

faculty/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django_downloadview.views.object import ObjectDownloadView

from assignments.models import AssignmentUpload
from auth.views import LoginView
from home.views import HomeView

from django.conf import settings
from django.conf.urls.static import static

download = ObjectDownloadView.as_view(model=AssignmentUpload, file_field='file')
urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^courses/', include('courses.urls')),
    url(r'^researches/', include('research.urls')),
    url(r'^exams/', include('exams.urls')),
    url(r'^assignments/', include('assignments.urls')),
    url(r'^subjects/', include('subjects.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^login/$', LoginView.user_login, name='login'),
    url(r'^logout/$', LoginView.user_logout, name='logout'),
    url('^media/uploads/(?P<slug>[A-Za-z0-9_-]+)/$', download, name='download'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exams/models.py
from django.db import models
from django.utils import timezone

from subjects.models import Subject
from users.models import Student


class ExamType(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Exam(models.Model):
    exam_type = models.ForeignKey(ExamType)
    subject = models.ForeignKey(Subject)
    hours = models.PositiveIntegerField()
    date = models.DateTimeField()

    class Meta:
        unique_together = ("exam_type", "subject", "date")

    def __str__(self):
        return '{} in {} on {}'.format(self.exam_type, self.subject, self.date)

    @property
    def is_upcoming(self):
        return self.date > timezone.now()


class Grade(models.Model):
    exam = models.ForeignKey(Exam)
    student = models.ForeignKey(Student)
    VALUE_CHOICES = (
        ('A+', 'A+'),
        ('A', 'A'),
        ('B+', 'B+'),
        ('B', 'B'),
        ('C+', 'C+'),
        ('C', 'C'),
        ('D+', 'D+'),
        ('D', 'D'),
        ('F', 'F')
    )
    value = models.CharField(max_length=2, choices=VALUE_CHOICES)

    def __str__(self):
        return '{} {} {}'.format(self.student, self.exam, self.value)

    @property
    def return_username(self):
        return self.student.user

exams/views.py
from django.views.generic import DetailView, ListView

from exams.models import Exam


class ExamsList(ListView):
    model = Exam


class ExamDetail(DetailView):
    model = Exam

templates/exams/exam_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="page-header">
    <h1>{% block title %} {{ exam.subject }}{% endblock %}</h1>
</div>
<table class="table table-bordered">
    <tr>
        <td>Topic</td>
        <td>{{ exam.subject }}</td>
    </tr>
    <tr>
        <td>Date</td>
        <td>{{ exam.date }}</td>
    </tr>
    <tr>
        <td>Exam Type</td>
        <td>{{ exam.exam_type }}</td>
    </tr>
    <tr>
        <td>Hours</td>
        <td>{{ exam.hours }} hrs</td>
    </tr>
  {% for grade in exam.grade_set.all %}
    {% if grade.return_username|escape == request.user.username  %}
    <tr>
        <td>Grade</td>
        <td>
          <h2>{{ grade.value }}</h2>
        </td>
    </tr>
    {% endif %}
  {% endfor %}
</table>



{% endblock %}

templates/exams/exam_list.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header">
    <h1>{% block title %}Exams{% endblock %}</h1>
</div>
<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">UPCOMING EXAMS</a></li>
    <li><a data-toggle="tab" href="#menu1">COMPLETED EXAMS</a></li>
</ul>
<br>

<div class="tab-content">
    <div id="home" class="tab-pane fade in active">
        <table class="table table-bordered">
            <tr>
                <th>Topic </th>
                <th>Deadline </th>
            </tr>
            {% for exam in exam_list %}
            {% if exam.is_upcoming %}
            <tr>
                <td><a href="{% url 'exam_detail' exam.pk %}">{{ exam.subject }}</a></td>
                <td>{{ exam.date }}</td>
            </tr>
            {% endif %}
            {% endfor %}
        </table>
    </div>
    <div id="menu1" class="tab-pane fade">
        <table class="table table-bordered">
            <tr>
                <th>Topic</th>
                <th>Deadline</th>
            </tr>
            {% for exam in exam_list %}
            {% if not exam.is_upcoming %}
            <tr>
                <td><a href="{% url 'exam_detail' exam.pk %}">{{ exam.subject }}</a></td>
                <td>{{ exam.date }}</td>
            </tr>

            {% endif %}
            {% endfor %}
        </table>
    </div>
</div>

<br>
{% endblock %}