assignments/urls.py
from django.conf.urls import url

from assignments.views import AssignmentDetail, AssignmentsList, AssignmentUploadView

urlpatterns = [
    url(r'^$',
        AssignmentsList.as_view(),
        name='assignments_list'),
    url(r'^(?P<pk>\d+)/?$',
        AssignmentDetail.as_view(),
        name='assignment_detail'),
    url(r'^(?P<pk>\d+)/upload$',
        AssignmentUploadView.as_view(),
        name='assignment_upload'),
]

exams/urls.py
from django.conf.urls import url

from exams.views import ExamsList, ExamDetail

urlpatterns = [
    url(r'^$',
        ExamsList.as_view(),
        name='exams_list'),
    url(r'^(?P<pk>\d+)/?$',
        ExamDetail.as_view(),
        name='exam_detail'),
    ]

faculty/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django_downloadview.views.object import ObjectDownloadView

from assignments.models import AssignmentUpload
from auth.views import LoginView
from home.views import HomeView

from django.conf import settings
from django.conf.urls.static import static

download = ObjectDownloadView.as_view(model=AssignmentUpload, file_field='file')
urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^courses/', include('courses.urls')),
    url(r'^researches/', include('research.urls')),
    url(r'^exams/', include('exams.urls')),
    url(r'^assignments/', include('assignments.urls')),
    url(r'^subjects/', include('subjects.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^login/$', LoginView.user_login, name='login'),
    url(r'^logout/$', LoginView.user_logout, name='logout'),
    url('^media/uploads/(?P<slug>[A-Za-z0-9_-]+)/$', download, name='download'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignments/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from subjects.models import Subject


class Assignment(models.Model):
    subject = models.ForeignKey(Subject)
    topic = models.CharField(max_length=30)
    description = models.TextField()
    deadline = models.DateTimeField()

    def __str__(self):
        return '{} on {}'.format(self.topic, self.subject)

    @property
    def is_upcoming(self):
        return self.deadline > timezone.now()

    def full_name(self):
        return self.user.get_full_name()


class AssignmentUpload(models.Model):
    assignment = models.ForeignKey(Assignment)
    user = models.ForeignKey(User)
    file = models.FileField(verbose_name='file', upload_to='uploads/')
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return 'Upload to {} as {} at {}, {}'.format(
            self.assignment, self.user, self.created, self.file.name)

assignments/forms.py
from django import forms

from assignments.models import AssignmentUpload


class AssignmentUploadForm(forms.ModelForm):
    class Meta:
        model = AssignmentUpload
        fields = ('file',)

    def __init__(self, *args, **kwargs):
        self.assignment = kwargs.pop('assignment')
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.instance.assignment = self.assignment
        self.instance.user = self.user

assignments/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView

from assignments.forms import AssignmentUploadForm
from assignments.models import Assignment, AssignmentUpload


class AssignmentsList(ListView):
    model = Assignment


class AssignmentDetail(DetailView):
    model = Assignment


class AssignmentUploadView(CreateView):
    model = AssignmentUpload
    form_class = AssignmentUploadForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        user = self.request.user
        kwargs['user'] = user
        kwargs['assignment'] = get_object_or_404(Assignment, pk=self.kwargs['pk'])
        return kwargs

    def get_success_url(self):
        return reverse('assignment_detail', args=(self.object.assignment.pk,))

templates/assignments/assignment_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="page-header">
    <h1>{% block title %} {{ assignment.subject }}{% endblock %}</h1>
  </div>
  <table class="table table-bordered">
    <tr>
      <td>Topic</td>
      <td>{{ assignment.topic }}</td>
    </tr>
    <tr>
      <td>Deadline</td>
      <td>{{ assignment.deadline }}</td>
    </tr>
    <tr>
      <td>Description</td>
      <td>{{ assignment.description }}</td>
    </tr>
  </table>

  <table class="table table-bordered">
  <tr><th>#</th><th>File</th><th>Date</th>
{% for group in user.groups.all %}
  {% if group.name == 'Staffs' %}
  <th>Student</th>
  {% endif %}
{% endfor %}
  </tr>
  {% for upload in assignment.assignmentupload_set.all %}
    {% if upload.user|escape ==  request.user.username %}
    <tr><td>{{ forloop.counter }}</td><td><a href="{{ upload.file.url }}">{{ upload.file.url }}</a></td><td>{{ upload.created }}</td></tr>
    {% endif %}
  {% for group in user.groups.all %}
  {% if group.name == 'Staffs' %}
      <tr><td>{{ forloop.counter }}</td><td><a href="{{ upload.file.url }}">{{ upload.file.url }}</a></td><td>{{ upload.created }}</td><td>{{ upload.user.get_full_name }}</td></tr>
    {% endif %}
  {% endfor %}
  {% endfor %}
  </table>

{% for group in user.groups.all %}
  {% if group.name == 'Students' %}
    {% if assignment.is_upcoming %}
      {% load render_partial %}
      {% render_partial 'assignments.views.AssignmentUploadView' pk=assignment.pk %}
    {% else %}
      <div class="alert alert-warning">
          Form has been closed, you should upload your assignment before {{ assignment.deadline }} !
      </div>
    {% endif %}
  {% endif%}
{% endfor %}

{% endblock %}

templates/assignments/assignment_list.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header">
    <h1>{% block title %}Assignments{% endblock %}</h1>
</div>
<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">UPCOMING ASSIGNMENTS</a></li>
    <li><a data-toggle="tab" href="#menu1">COMPLETED ASSIGNMENTS</a></li>
</ul>
<br>
<div class="tab-content">
    <div id="home" class="tab-pane fade in active">
        <table class="table table-bordered">
            <tr>
                <th>Topic</th>
                <th>Deadline</th>
            </tr>
            {% for assignment in assignment_list %}
            {% if assignment.is_upcoming %}
            <tr>
                <td><a href="{% url 'assignment_detail' assignment.pk %}">{{ assignment.topic }}</a></td>
                <td>{{ assignment.deadline }}</td>
            </tr>
            {% endif %}
            {% endfor %}
        </table>
    </div>
    <div id="menu1" class="tab-pane fade">
        <table class="table table-bordered">
            <tr>
                <th>Topic</th>
                <th>Deadline</th>
            </tr>
            {% for assignment in assignment_list %}
            {% if not assignment.is_upcoming %}
            <tr>
                <td><a href="{% url 'assignment_detail' assignment.pk %}">{{ assignment.topic }}</a></td>
                <td>{{ assignment.deadline }}</td>
            </tr>

            {% endif %}
            {% endfor %}
        </table>
    </div>
</div>


{% endblock %}

templates/assignments/assignmentupload_form.html
{% block content %}
{#  <h1>Upload for {{ form.assignment }}</h1>#}

  <form method="post" enctype="multipart/form-data"
        action="{% url 'assignment_upload' form.assignment.pk %}">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" class="btn btn-primary btn-file" value="Upload"/>
  </form>
  <br>
  <br>
  <br>
{% endblock %}